---
name: ci
on: push

jobs:
  test-python:
    name: test python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pipenv'
      - run: pip install pipenv
      - run: pipenv install --dev -v
      - run: pipenv run coverage run -m pytest
      - run: pipenv run mypy .
      - run: pipenv run pylint --enable-all-extensions --fail-under 5 app
      - uses: codecov/codecov-action@v4
        with:
          files: .coverage
